packages:
  - adduser
  - apparmor
  - apport
  - apport-core-dump-handler
  - apport-symptoms
  - appstream
  - apt
  - apt-utils
  - base-files
  - base-passwd
  - bash
  - bash-completion
  - bc
  - bcache-tools
  - bind9-dnsutils
  - bind9-host
  - bind9-libs:amd64
  - binutils
  - binutils-common:amd64
  - binutils-x86-64-linux-gnu
  - bolt
  - bpfcc-tools
  - bpftrace
  - bsdextrautils
  - bsdutils
  - btrfs-progs
  - busybox-initramfs
  - busybox-static
  - byobu
  - ca-certificates
  - chrony
  - cifs-utils
  - cloud-guest-utils
  - cloud-init
  - cloud-initramfs-copymods
  - cloud-initramfs-dyn-netconf
  - command-not-found
  - console-setup
  - console-setup-linux
  - coreutils
  - cpio
  - cron
  - cron-daemon-common
  - cryptsetup
  - cryptsetup-bin
  - cryptsetup-initramfs
  - curl
  - dash
  - dbus
  - dbus-bin
  - dbus-daemon
  - dbus-session-bus-common
  - dbus-system-bus-common
  - dbus-user-session
  - debconf
  - debconf-i18n
  - debianutils
  - dhcpcd-base
  - diffutils
  - dirmngr
  - distro-info
  - distro-info-data
  - dmeventd
  - dmidecode
  - dmsetup
  - dosfstools
  - dpkg
  - dracut-install
  - e2fsprogs
  - e2fsprogs-l10n
  - eatmydata
  - ed
  - efibootmgr
  - eject
  - ethtool
  - fdisk
  - file
  - finalrd
  - findutils
  - fonts-ubuntu-console
  - friendly-recovery
  - ftp
  - fuse3
  - fwupd
  - fwupd-signed
  - gawk
  - gcc-12-base:amd64
  - gcc-14-base:amd64
  - gdisk
  - gettext-base
  - gir1.2-girepository-2.0:amd64
  - gir1.2-glib-2.0:amd64
  - gir1.2-packagekitglib-1.0
  - git
  - git-man
  - gnupg
  - gnupg-l10n
  - gnupg-utils
  - gpg
  - gpg-agent
  - gpgconf
  - gpgsm
  - gpgv
  - gpg-wks-client
  - gpg-wks-server
  - grep
  - groff-base
  - grub2-common
  - grub-common
  - grub-efi-amd64-bin
  - grub-efi-amd64-signed
  - grub-gfxpayload-lists
  - grub-pc
  - grub-pc-bin
  - gzip
  - hdparm
  - hostname
  - htop
  - hwdata
  - ibverbs-providers:amd64
  - ieee-data
  - inetutils-telnet
  - info
  - init
  - initramfs-tools
  - initramfs-tools-bin
  - initramfs-tools-core
  - init-system-helpers
  - install-info
  - iproute2
  - iptables
  - iputils-ping
  - iputils-tracepath
  - irqbalance
  - isc-dhcp-client
  - isc-dhcp-common
  - iso-codes
  - jq
  - kbd
  - keyboard-configuration
  - keyboxd
  - keyutils
  - klibc-utils
  - kmod
  - kpartx
  - krb5-locales
  - landscape-common
  - less
  - libacl1:amd64
  - libaio1:amd64
  - libaio1t64:amd64
  - libapparmor1:amd64
  - libappstream4:amd64
  - libappstream5:amd64
  - libapt-pkg6.0:amd64
  - libapt-pkg6.0t64:amd64
  - libarchive13:amd64
  - libarchive13t64:amd64
  - libargon2-1:amd64
  - libassuan0:amd64
  - libatasmart4:amd64
  - libatm1:amd64
  - libatm1t64:amd64
  - libattr1:amd64
  - libaudit1:amd64
  - libaudit-common
  - libbinutils:amd64
  - libblkid1:amd64
  - libblockdev2:amd64
  - libblockdev3:amd64
  - libblockdev-crypto2:amd64
  - libblockdev-crypto3:amd64
  - libblockdev-fs2:amd64
  - libblockdev-fs3:amd64
  - libblockdev-loop2:amd64
  - libblockdev-loop3:amd64
  - libblockdev-mdraid3:amd64
  - libblockdev-nvme3:amd64
  - libblockdev-part2:amd64
  - libblockdev-part3:amd64
  - libblockdev-part-err2:amd64
  - libblockdev-swap2:amd64
  - libblockdev-swap3:amd64
  - libblockdev-utils2:amd64
  - libblockdev-utils3:amd64
  - libbpf0:amd64
  - libbpf1:amd64
  - libbpfcc:amd64
  - libbrotli1:amd64
  - libbsd0:amd64
  - libbytesize1:amd64
  - libbytesize-common
  - libbz2-1.0:amd64
  - libc6:amd64
  - libcap2:amd64
  - libcap2-bin
  - libcap-ng0:amd64
  - libc-bin
  - libcbor0.10:amd64
  - libcbor0.8:amd64
  - libclang1-18
  - libclang-cpp18
  - libcom-err2:amd64
  - libcrypt1:amd64
  - libcryptsetup12:amd64
  - libctf0:amd64
  - libctf-nobfd0:amd64
  - libcurl3-gnutls:amd64
  - libcurl3t64-gnutls:amd64
  - libcurl4:amd64
  - libcurl4t64:amd64
  - libdb5.3:amd64
  - libdb5.3t64:amd64
  - libdbus-1-3:amd64
  - libdebconfclient0:amd64
  - libdevmapper1.02.1:amd64
  - libdevmapper-event1.02.1:amd64
  - libdns-export1110
  - libdrm2:amd64
  - libdrm-common
  - libduktape207:amd64
  - libdw1:amd64
  - libdw1t64:amd64
  - libeatmydata1:amd64
  - libedit2:amd64
  - libefiboot1:amd64
  - libefiboot1t64:amd64
  - libefivar1:amd64
  - libefivar1t64:amd64
  - libelf1:amd64
  - libelf1t64:amd64
  - liberror-perl
  - libestr0:amd64
  - libevdev2:amd64
  - libevent-core-2.1-7:amd64
  - libevent-core-2.1-7t64:amd64
  - libexpat1:amd64
  - libext2fs2:amd64
  - libext2fs2t64:amd64
  - libfastjson4:amd64
  - libfdisk1:amd64
  - libffi8:amd64
  - libfido2-1:amd64
  - libflashrom1:amd64
  - libfreetype6:amd64
  - libfribidi0:amd64
  - libftdi1-2:amd64
  - libfuse3-3:amd64
  - libfwupd2:amd64
  - libfwupdplugin5:amd64
  - libgcab-1.0-0:amd64
  - libgcc-s1:amd64
  - libgcrypt20:amd64
  - libgdbm6:amd64
  - libgdbm6t64:amd64
  - libgdbm-compat4:amd64
  - libgdbm-compat4t64:amd64
  - libgirepository-1.0-1:amd64
  - libglib2.0-0:amd64
  - libglib2.0-0t64:amd64
  - libglib2.0-bin
  - libglib2.0-data
  - libgmp10:amd64
  - libgnutls30:amd64
  - libgnutls30t64:amd64
  - libgpg-error0:amd64
  - libgpg-error-l10n
  - libgpgme11:amd64
  - libgpgme11t64:amd64
  - libgpm2:amd64
  - libgssapi-krb5-2:amd64
  - libgstreamer1.0-0:amd64
  - libgudev-1.0-0:amd64
  - libgusb2:amd64
  - libhogweed6:amd64
  - libhogweed6t64:amd64
  - libibverbs1:amd64
  - libicu70:amd64
  - libicu74:amd64
  - libidn2-0:amd64
  - libinih1:amd64
  - libintl-perl
  - libintl-xs-perl
  - libip4tc2:amd64
  - libip6tc2:amd64
  - libisc-export1105:amd64
  - libisns0:amd64
  - libisns0t64:amd64
  - libjansson4:amd64
  - libjcat1:amd64
  - libjq1:amd64
  - libjson-c5:amd64
  - libjson-glib-1.0-0:amd64
  - libjson-glib-1.0-common
  - libk5crypto3:amd64
  - libkeyutils1:amd64
  - libklibc:amd64
  - libkmod2:amd64
  - libkrb5-3:amd64
  - libkrb5support0:amd64
  - libksba8:amd64
  - libldap-2.5-0:amd64
  - libldap2:amd64
  - libldap-common
  - libllvm18:amd64
  - liblmdb0:amd64
  - liblocale-gettext-perl
  - liblvm2cmd2.03:amd64
  - liblz4-1:amd64
  - liblzma5:amd64
  - liblzo2-2:amd64
  - libmagic1:amd64
  - libmagic1t64:amd64
  - libmagic-mgc
  - libmaxminddb0:amd64
  - libmbim-glib4:amd64
  - libmbim-proxy
  - libmbim-utils
  - libmd0:amd64
  - libmm-glib0:amd64
  - libmnl0:amd64
  - libmodule-find-perl
  - libmodule-scandeps-perl
  - libmount1:amd64
  - libmpdec3:amd64
  - libmpfr6:amd64
  - libmspack0:amd64
  - libmspack0t64:amd64
  - libncurses6:amd64
  - libncursesw6:amd64
  - libnetfilter-conntrack3:amd64
  - libnetplan0:amd64
  - libnetplan1:amd64
  - libnettle8:amd64
  - libnettle8t64:amd64
  - libnewt0.52:amd64
  - libnfnetlink0:amd64
  - libnftables1:amd64
  - libnftnl11:amd64
  - libnghttp2-14:amd64
  - libnl-3-200:amd64
  - libnl-genl-3-200:amd64
  - libnl-route-3-200:amd64
  - libnpth0:amd64
  - libnpth0t64:amd64
  - libnsl2:amd64
  - libnspr4:amd64
  - libnss3:amd64
  - libnss-systemd:amd64
  - libntfs-3g89
  - libntfs-3g89t64:amd64
  - libnuma1:amd64
  - libnvme1t64
  - libonig5:amd64
  - libopeniscsiusr
  - libp11-kit0:amd64
  - libpackagekit-glib2-18:amd64
  - libpam0g:amd64
  - libpam-cap:amd64
  - libpam-modules:amd64
  - libpam-modules-bin
  - libpam-runtime
  - libpam-systemd:amd64
  - libparted2:amd64
  - libparted2t64:amd64
  - libparted-fs-resize0:amd64
  - libpcap0.8:amd64
  - libpcap0.8t64:amd64
  - libpci3:amd64
  - libpcre2-8-0:amd64
  - libpcre3:amd64
  - libperl5.34:amd64
  - libperl5.38t64:amd64
  - libpipeline1:amd64
  - libplymouth5:amd64
  - libpng16-16:amd64
  - libpng16-16t64:amd64
  - libpolkit-agent-1-0:amd64
  - libpolkit-gobject-1-0:amd64
  - libpopt0:amd64
  - libproc2-0:amd64
  - libproc-processtable-perl:amd64
  - libprocps8:amd64
  - libprotobuf-c1:amd64
  - libpsl5:amd64
  - libpsl5t64:amd64
  - libpython3.10:amd64
  - libpython3.10-minimal:amd64
  - libpython3.10-stdlib:amd64
  - libpython3.12-minimal:amd64
  - libpython3.12-stdlib:amd64
  - libpython3.12t64:amd64
  - libpython3-stdlib:amd64
  - libqmi-glib5:amd64
  - libqmi-proxy
  - libqmi-utils
  - libqrtr-glib0:amd64
  - libreadline8:amd64
  - libreadline8t64:amd64
  - libreiserfscore0t64
  - librtmp1:amd64
  - libsasl2-2:amd64
  - libsasl2-modules:amd64
  - libsasl2-modules-db:amd64
  - libseccomp2:amd64
  - libselinux1:amd64
  - libsemanage2:amd64
  - libsemanage-common
  - libsensors5:amd64
  - libsensors-config
  - libsepol2:amd64
  - libsgutils2-1.46-2:amd64
  - libsgutils2-2:amd64
  - libsigsegv2:amd64
  - libslang2:amd64
  - libsmartcols1:amd64
  - libsmbios-c2
  - libsodium23:amd64
  - libsort-naturally-perl
  - libsqlite3-0:amd64
  - libss2:amd64
  - libssh-4:amd64
  - libssl3:amd64
  - libssl3t64:amd64
  - libstdc++6:amd64
  - libstemmer0d:amd64
  - libsystemd0:amd64
  - libsystemd-shared:amd64
  - libtalloc2:amd64
  - libtasn1-6:amd64
  - libtcl8.6:amd64
  - libterm-readkey-perl
  - libtevent0:amd64
  - libtext-charwidth-perl
  - libtext-charwidth-perl:amd64
  - libtext-iconv-perl
  - libtext-iconv-perl:amd64
  - libtext-wrapi18n-perl
  - libtinfo6:amd64
  - libtirpc3:amd64
  - libtirpc3t64:amd64
  - libtirpc-common
  - libtraceevent1:amd64
  - libtraceevent1-plugin:amd64
  - libtracefs1:amd64
  - libtss2-esys-3.0.2-0:amd64
  - libtss2-esys-3.0.2-0t64:amd64
  - libtss2-mu0:amd64
  - libtss2-mu-4.0.1-0t64:amd64
  - libtss2-rc0:amd64
  - libtss2-rc0t64:amd64
  - libtss2-sys1:amd64
  - libtss2-sys1t64:amd64
  - libtss2-tcti-cmd0:amd64
  - libtss2-tcti-cmd0t64:amd64
  - libtss2-tcti-device0:amd64
  - libtss2-tcti-device0t64:amd64
  - libtss2-tcti-mssim0:amd64
  - libtss2-tcti-mssim0t64:amd64
  - libtss2-tcti-swtpm0:amd64
  - libtss2-tcti-swtpm0t64:amd64
  - libuchardet0:amd64
  - libudev1:amd64
  - libudisks2-0:amd64
  - libunistring2:amd64
  - libunistring5:amd64
  - libunwind8:amd64
  - liburcu8:amd64
  - liburcu8t64:amd64
  - libusb-1.0-0:amd64
  - libutempter0:amd64
  - libuuid1:amd64
  - libuv1:amd64
  - libuv1t64:amd64
  - libvolume-key1
  - libvolume-key1:amd64
  - libwbclient0:amd64
  - libwrap0:amd64
  - libx11-6:amd64
  - libx11-data
  - libxau6:amd64
  - libxcb1:amd64
  - libxdmcp6:amd64
  - libxext6:amd64
  - libxkbcommon0:amd64
  - libxml2:amd64
  - libxmlb2:amd64
  - libxmlsec1:amd64
  - libxmlsec1-openssl:amd64
  - libxmlsec1t64:amd64
  - libxmlsec1t64-openssl:amd64
  - libxmuu1:amd64
  - libxslt1.1:amd64
  - libxtables12:amd64
  - libxxhash0:amd64
  - libyaml-0-2:amd64
  - libzstd1:amd64
  - linux-azure
  - linux-azure-6.8-cloud-tools-6.8.0-1018
  - linux-azure-6.8-headers-6.8.0-1018
  - linux-azure-6.8-tools-6.8.0-1018
  - linux-azure-cloud-tools-6.8.0-1018
  - linux-azure-fde
  - linux-azure-headers-6.8.0-1018
  - linux-azure-tools-6.8.0-1018
  - linux-base
  - linux-base-sgx
  - linux-cloud-tools-6.8.0-1018-azure
  - linux-cloud-tools-azure
  - linux-cloud-tools-common
  - linux-headers-6.8.0-1018-azure
  - linux-headers-azure
  - linux-image-6.8.0-1018-azure
  - linux-image-6.8.0-1018-azure-fde
  - linux-image-azure
  - linux-image-azure-fde
  - linux-modules-6.8.0-1018-azure
  - linux-tools-6.8.0-1018-azure
  - linux-tools-azure
  - linux-tools-common
  - locales
  - login
  - logrotate
  - logsave
  - lsb-base
  - lsb-release
  - lshw
  - lsof
  - lsscsi
  - lvm2
  - lxd-agent-loader
  - lxd-installer
  - man-db
  - manpages
  - mawk
  - mdadm
  - media-types
  - modemmanager
  - mokutil
  - motd-news-config
  - mount
  - mtr-tiny
  - multipath-tools
  - nano
  - ncurses-base
  - ncurses-bin
  - ncurses-term
  - needrestart
  - netbase
  - netcat-openbsd
  - netplan-generator
  - netplan.io
  - networkd-dispatcher
  - nftables
  - ntfs-3g
  - nullboot
  - numactl
  - nvme-cli
  - open-iscsi
  - openssh-client
  - openssh-server
  - openssh-sftp-server
  - openssl
  - open-vm-tools
  - os-prober
  - overlayroot
  - packagekit
  - packagekit-tools
  - parted
  - passwd
  - pastebinit
  - patch
  - pci.ids
  - pciutils
  - perl
  - perl-base
  - perl-modules-5.34
  - perl-modules-5.38
  - pinentry-curses
  - pkexec
  - plymouth
  - plymouth-theme-ubuntu-text
  - policykit-1
  - polkitd
  - pollinate
  - powermgmt-base
  - procps
  - psmisc
  - publicsuffix
  - python3
  - python3.10
  - python3.10-minimal
  - python3.12
  - python3.12-minimal
  - python3-apport
  - python3-apt
  - python3-attr
  - python3-automat
  - python3-babel
  - python3-bcrypt
  - python3-blinker
  - python3-boto3
  - python3-botocore
  - python3-bpfcc
  - python3-certifi
  - python3-cffi-backend:amd64
  - python3-chardet
  - python3-click
  - python3-colorama
  - python3-commandnotfound
  - python3-configobj
  - python3-constantly
  - python3-cryptography
  - python3-dateutil
  - python3-dbus
  - python3-debconf
  - python3-debian
  - python3-distro
  - python3-distro-info
  - python3-distupgrade
  - python3-distutils
  - python3-gdbm:amd64
  - python3-gi
  - python3-hamcrest
  - python3-httplib2
  - python3-hyperlink
  - python3-idna
  - python3-importlib-metadata
  - python3-incremental
  - python3-jeepney
  - python3-jinja2
  - python3-jmespath
  - python3-jsonpatch
  - python3-json-pointer
  - python3-jsonschema
  - python3-jwt
  - python3-keyring
  - python3-launchpadlib
  - python3-lazr.restfulclient
  - python3-lazr.uri
  - python3-lib2to3
  - python3-magic
  - python3-markdown-it
  - python3-markupsafe
  - python3-mdurl
  - python3-minimal
  - python3-more-itertools
  - python3-netaddr
  - python3-netifaces:amd64
  - python3-netplan
  - python3-newt:amd64
  - python3-oauthlib
  - python3-openssl
  - python3-packaging
  - python3-parted
  - python3-pexpect
  - python3-pkg-resources
  - python3-problem-report
  - python3-ptyprocess
  - python3-pyasn1
  - python3-pyasn1-modules
  - python3-pygments
  - python3-pyparsing
  - python3-pyrsistent:amd64
  - python3-requests
  - python3-rich
  - python3-s3transfer
  - python3-secretstorage
  - python3-serial
  - python3-service-identity
  - python3-setuptools
  - python3-six
  - python3-software-properties
  - python3-systemd
  - python3-twisted
  - python3-typing-extensions
  - python3-tz
  - python3-update-manager
  - python3-urllib3
  - python3-wadllib
  - python3-yaml
  - python3-zipp
  - python3-zope.interface
  - python-apt-common
  - python-babel-localedata
  - readline-common
  - rsync
  - rsyslog
  - run-one
  - sbsigntool
  - screen
  - secureboot-db
  - sed
  - sensible-utils
  - sg3-utils
  - sg3-utils-udev
  - sgml-base
  - shared-mime-info
  - shim-signed
  - snapd
  - software-properties-common
  - sosreport
  - squashfs-tools
  - ssh-import-id
  - strace
  - sudo
  - sysstat
  - systemd
  - systemd-dev
  - systemd-hwe-hwdb
  - systemd-resolved
  - systemd-sysv
  - sysvinit-utils
  - tar
  - tcl
  - tcl8.6
  - tcpdump
  - telnet
  - thin-provisioning-tools
  - time
  - tmux
  - tnftp
  - tpm-udev
  - trace-cmd
  - tzdata
  - tzdata-legacy
  - ubuntu-advantage-tools
  - ubuntu-kernel-accessories
  - ubuntu-keyring
  - ubuntu-minimal
  - ubuntu-pro-client
  - ubuntu-pro-client-l10n
  - ubuntu-release-upgrader-core
  - ubuntu-server
  - ubuntu-standard
  - ucf
  - udev
  - udisks2
  - ufw
  - unattended-upgrades
  - update-manager-core
  - update-notifier-common
  - usb.ids
  - usb-modeswitch
  - usb-modeswitch-data
  - usbutils
  - usrmerge
  - util-linux
  - uuid-runtime
  - vim
  - vim-common
  - vim-runtime
  - vim-tiny
  - walinuxagent
  - wget
  - whiptail
  - xauth
  - xdg-user-dirs
  - xfsprogs
  - xkb-data
  - xml-core
  - xxd
  - xz-utils
  - zerofree
  - zlib1g:amd64
  - zstd
